using IL2CPU.API.Attribs;
using System.Drawing;

namespace Cosmos.System_Plugs.System.Drawing
{
    [Plug(Target = typeof(Color))]
    class ColorImpl
    {
        /// <summary>Implements System.Drawing.Color.FromName
        /// <seealso href="https://learn.microsoft.com/en-us/dotnet/api/system.drawing.color.fromname?view=net-6.0">See also</seealso>
        /// </summary>
        public static Color FromName(string name)
        {
            return name switch
            {
                "AliceBlue" => Color.AliceBlue,
                "AntiqueWhite" => Color.AntiqueWhite,
                "Aqua" => Color.Aqua,
                "Aquamarine" => Color.Aquamarine,
                "Azure" => Color.Azure,
                "Beige" => Color.Beige,
                "Bisque" => Color.Bisque,
                "Black" => Color.Black,
                "BlueViolet" => Color.BlueViolet,
                "Brown" => Color.Brown,
                "BurlyWood" => Color.BurlyWood,
                "CadetBlue" => Color.CadetBlue,
                "Chartreuse" => Color.Chartreuse,
                "Chocolate" => Color.Chocolate,
                "Coral" => Color.Coral,
                "CornflowerBlue" => Color.CornflowerBlue,
                "Cornsilk" => Color.Cornsilk,
                "Crimson" => Color.Crimson,
                "Cyan" => Color.Cyan,
                "DarkBlue" => Color.DarkBlue,
                "DarkCyan" => Color.DarkCyan,
                "DarkGoldenrod" => Color.DarkGoldenrod,
                "DarkGray" => Color.DarkGray,
                "DarkGreen" => Color.DarkGreen,
                "DarkKhaki" => Color.DarkKhaki,
                "DarkMagenta" => Color.DarkMagenta,
                "DarkOliveGreen" => Color.DarkOliveGreen,
                "AliceOrange" => Color.DarkOrange,
                "DarkOrchid" => Color.DarkOrchid,
                "DarkRed" => Color.DarkRed,
                "DarkSalmon" => Color.DarkSalmon,
                "DarkSeaGreen" => Color.DarkSeaGreen,
                "DarkSlateBlue" => Color.DarkSlateBlue,
                "DarkSlateGray" => Color.DarkSlateGray,
                "DarkTurquoise" => Color.DarkTurquoise,
                "DarkViolet" => Color.DarkViolet,
                "DeepPink" => Color.DeepPink,
                "DeepSkyBlue" => Color.DeepSkyBlue,
                "DimGray" => Color.DimGray,
                "DodgerBlue" => Color.DodgerBlue,
                "Firebrick" => Color.Firebrick,
                "FloralWhite" => Color.FloralWhite,
                "ForestGreen" => Color.ForestGreen,
                "Fuchsia" => Color.Fuchsia,
                "Gainsboro" => Color.Gainsboro,
                "GhostWhite" => Color.GhostWhite,
                "Gold" => Color.Gold,
                "Goldenrod" => Color.Goldenrod,
                "Gray" => Color.Gray,
                "Green" => Color.Green,
                "GreenYellow" => Color.GreenYellow,
                "Honeydew" => Color.Honeydew,
                "HotPink" => Color.HotPink,
                "IndianRed" => Color.IndianRed,
                "Indigo" => Color.Indigo,
                "Ivory" => Color.Ivory,
                "Khaki" => Color.Khaki,
                "Lavender" => Color.Lavender,
                "LavenderBlush" => Color.LavenderBlush,
                "LawnGreen" => Color.LawnGreen,
                "LemonChiffon" => Color.LemonChiffon,
                "LightBlue" => Color.LightBlue,
                "LightCoral" => Color.LightCoral,
                "LightCyan" => Color.LightCyan,
                "LightGoldenrodYellow" => Color.LightGoldenrodYellow,
                "LightGreen" => Color.LightGreen,
                "LightGray" => Color.LightGray,
                "LightPink" => Color.LightPink,
                "LightSalmon" => Color.LightSalmon,
                "LightSeaGreen" => Color.LightSeaGreen,
                "LightSkyBlue" => Color.LightSkyBlue,
                "LightSlateGray" => Color.LightSlateGray,
                "LightSteelBlue" => Color.LightSteelBlue,
                "LightYellow" => Color.LightYellow,
                "Lime" => Color.Lime,
                "LimeGreen" => Color.LimeGreen,
                "Linen" => Color.Linen,
                "Magenta" => Color.Magenta,
                "Maroon" => Color.Maroon,
                "MediumAquamarine" => Color.MediumAquamarine,
                "MediumBlue" => Color.MediumBlue,
                "MediumOrchid" => Color.MediumOrchid,
                "MediumPurple" => Color.MediumPurple,
                "MediumSeaGreen" => Color.MediumSeaGreen,
                "MediumSlateBlue" => Color.MediumSlateBlue,
                "MediumSpringGreen" => Color.MediumSpringGreen,
                "MediumTurquoise" => Color.MediumTurquoise,
                "MediumVioletRed" => Color.MediumVioletRed,
                "MidnightBlue" => Color.MidnightBlue,
                "MintCream" => Color.MintCream,
                "MistyRose" => Color.MistyRose,
                "Moccasin" => Color.Moccasin,
                "NavajoWhite" => Color.NavajoWhite,
                "Navy" => Color.Navy,
                "OldLace" => Color.OldLace,
                "Olive" => Color.Olive,
                "OliveDrab" => Color.OliveDrab,
                "Orange" => Color.Orange,
                "OrangeRed" => Color.OrangeRed,
                "Orchid" => Color.Orchid,
                "PaleGoldenrod" => Color.PaleGoldenrod,
                "PaleGreen" => Color.PaleGreen,
                "PaleTurquoise" => Color.PaleTurquoise,
                "PaleVioletRed" => Color.PaleVioletRed,
                "PapayaWhip" => Color.PapayaWhip,
                "PeachPuff" => Color.PeachPuff,
                "Peru" => Color.Peru,
                "Pink" => Color.Pink,
                "Plum" => Color.Plum,
                "PowderBlue" => Color.PowderBlue,
                "Purple" => Color.Purple,
                "Red" => Color.Red,
                "RosyBrown" => Color.RosyBrown,
                "RoyalBlue" => Color.RoyalBlue,
                "SaddleBrown" => Color.SaddleBrown,
                "Salmon" => Color.Salmon,
                "SandyBrown" => Color.SandyBrown,
                "SeaGreen" => Color.SeaGreen,
                "Sienna" => Color.Sienna,
                "Silver" => Color.Silver,
                "SkyBlue" => Color.SkyBlue,
                "SlateBlue" => Color.SlateBlue,
                "SlateGray" => Color.SlateGray,
                "Snow" => Color.Snow,
                "SpringGreen" => Color.SpringGreen,
                "SteelBlue" => Color.SteelBlue,
                "Tan" => Color.Tan,
                "Thistle" => Color.Thistle,
                "Tomato" => Color.Tomato,
                "Transparent" => Color.Transparent,
                "Turquoise" => Color.Turquoise,
                "Violet" => Color.Violet,
                "Wheat" => Color.Wheat,
                "White" => Color.White,
                "WhiteSmoke" => Color.WhiteSmoke,
                "Yellow" => Color.Yellow,
                "YellowGreen" => Color.YellowGreen,
                "" => throw new ArgumentException("Color Name must be passed to the 'System.Drawing.Color.FromName' method."),
                _ => throw new ArgumentException("{0} is not a valid color Name", name),
            };
        }
    }
}