// This code is licensed under the BSD 3-Clause license (see LICENSE for details)

using System;

namespace Cosmos.Kernel.Drivers.Svga;

/// <summary>SVGA3dDeclUsage: what a vertex attribute stream carries (svga3d_reg.h).</summary>
internal enum SVGA3dDeclUsage
{
    SVGA3D_DECLUSAGE_POSITION = 0,
    SVGA3D_DECLUSAGE_BLENDWEIGHT,
    SVGA3D_DECLUSAGE_BLENDINDICES,
    SVGA3D_DECLUSAGE_NORMAL,
    SVGA3D_DECLUSAGE_PSIZE,
    SVGA3D_DECLUSAGE_TEXCOORD,
    SVGA3D_DECLUSAGE_TANGENT,
    SVGA3D_DECLUSAGE_BINORMAL,
    SVGA3D_DECLUSAGE_TESSFACTOR,
    SVGA3D_DECLUSAGE_POSITIONT,
    SVGA3D_DECLUSAGE_COLOR,
    SVGA3D_DECLUSAGE_FOG,
    SVGA3D_DECLUSAGE_DEPTH,
    SVGA3D_DECLUSAGE_SAMPLE,
    SVGA3D_DECLUSAGE_MAX
}
