using System;
using System.IO;
using Mono.Cecil;
using Mono.Cecil.Cil;
using CPU = Indy.IL2CPU.Assembler.X86;

namespace Indy.IL2CPU.IL.X86 {
	[OpCode(Code.Br_S)]
	public class Br_S: Op {
		private bool mIsFake;
		public Br_S(Mono.Cecil.Cil.Instruction aInstruction, MethodInformation aMethodInfo)
			: base(aInstruction, aMethodInfo) {
			// next physical opcode is +2, because the opcode is singlebyte, and has a byte as param
			mIsFake = aInstruction.Next.Offset == (aInstruction.Offset + 2);
		}
		public override void Assemble() {
			if (!mIsFake) {
				throw new NotImplementedException("This file has been autogenerated and not been changed afterwards!");
			}
		}
	}
}