use32
org 0x200000
			sub byte AL, AL
			sub byte AL, AH
			sub byte AL, BL
			sub byte AL, BH
			sub byte AL, CL
			sub byte AL, CH
			sub byte AL, DL
			sub byte AL, DH
			sub byte AH, AL
			sub byte AH, AH
			sub byte AH, BL
			sub byte AH, BH
			sub byte AH, CL
			sub byte AH, CH
			sub byte AH, DL
			sub byte AH, DH
			sub byte BL, AL
			sub byte BL, AH
			sub byte BL, BL
			sub byte BL, BH
			sub byte BL, CL
			sub byte BL, CH
			sub byte BL, DL
			sub byte BL, DH
			sub byte BH, AL
			sub byte BH, AH
			sub byte BH, BL
			sub byte BH, BH
			sub byte BH, CL
			sub byte BH, CH
			sub byte BH, DL
			sub byte BH, DH
			sub byte CL, AL
			sub byte CL, AH
			sub byte CL, BL
			sub byte CL, BH
			sub byte CL, CL
			sub byte CL, CH
			sub byte CL, DL
			sub byte CL, DH
			sub byte CH, AL
			sub byte CH, AH
			sub byte CH, BL
			sub byte CH, BH
			sub byte CH, CL
			sub byte CH, CH
			sub byte CH, DL
			sub byte CH, DH
			sub byte DL, AL
			sub byte DL, AH
			sub byte DL, BL
			sub byte DL, BH
			sub byte DL, CL
			sub byte DL, CH
			sub byte DL, DL
			sub byte DL, DH
			sub byte DH, AL
			sub byte DH, AH
			sub byte DH, BL
			sub byte DH, BH
			sub byte DH, CL
			sub byte DH, CH
			sub byte DH, DL
			sub byte DH, DH
