// This code is licensed under the BSD 3-Clause license (see LICENSE for details)

using Cosmos.Kernel.SourceGenerators;

namespace Cosmos.Tests.SourceGenerators;

/// <summary>
/// The exact text the generator is expected to emit, assembled the same way
/// a reader would write it by hand, so a test states the manifest it wants
/// as a list of registrations.
/// </summary>
internal static class GeneratedText
{
    private const string Registry = "global::Cosmos.Kernel.HAL.DriverKit.DriverRegistry";
    private const string Features = "global::Cosmos.Kernel.System.KernelFeatures";

    /// <summary>The <c>[GeneratedCode]</c> line, stamped with the generator's own name and assembly version.</summary>
    public static string GeneratedCodeAttribute =>
        $"[global::System.CodeDom.Compiler.GeneratedCode(\"{typeof(CosmosEntryPointGenerator).FullName}\", \"{typeof(CosmosEntryPointGenerator).Assembly.GetName().Version}\")]";

    /// <summary>The whole of <c>CosmosEntryPoint.g.cs</c> for <paramref name="kernelClass"/>.</summary>
    /// <param name="kernelClass">The kernel type the entry point constructs.</param>
    public static string EntryPoint(string kernelClass) =>
        "// <auto-generated/>\n"
        + "namespace Cosmos.Kernel.System.Internal;\n\n"
        + "/// <summary>The kernel's entry point: registers the drivers in the manifest, then the kernel, and starts it.</summary>\n"
        + GeneratedCodeAttribute + "\n"
        + "public static class CosmosEntryPoint\n{\n"
        + "    /// <summary>Called by the runtime startup code once the managed world is up.</summary>\n"
        + "    public static void Main()\n    {\n"
        + "        global::Cosmos.Kernel.System.Internal.DriverManifest.Register();\n"
        + $"        global::Cosmos.Kernel.System.Global.RegisterKernel(new global::{kernelClass}());\n"
        + "        global::Cosmos.Kernel.System.Global.StartKernel();\n"
        + "    }\n}\n";

    /// <summary>The whole of <c>DriverManifest.g.cs</c> whose <c>Register</c> body is <paramref name="statements"/>, in order.</summary>
    /// <param name="statements">Statements from <see cref="Registration"/> and <see cref="GuardedRegistration"/>; none for an empty manifest.</param>
    public static string Manifest(params string[] statements) =>
        "// <auto-generated/>\n"
        + "// The driver registry is on the experimental driver kit seam (COSMOS0003).\n"
        + "// This file is generated, so it acknowledges the seam for itself alone;\n"
        + "// a driver this kernel declares still meets the diagnostic in its own code.\n"
        + "#pragma warning disable COSMOS0003\n"
        + "namespace Cosmos.Kernel.System.Internal;\n\n"
        + "/// <summary>The drivers this kernel carries, registered in manifest order before the kernel starts.</summary>\n"
        + GeneratedCodeAttribute + "\n"
        + "internal static class DriverManifest\n{\n"
        + "    /// <summary>Registers every driver the manifest lists with the driver registry.</summary>\n"
        + "    public static void Register()\n    {\n"
        + string.Concat(statements)
        + "    }\n}\n";

    /// <summary>An unguarded registration of <paramref name="fullName"/>.</summary>
    /// <param name="fullName">The driver's full type name without <c>global::</c>.</param>
    public static string Registration(string fullName) =>
        $"        {Registry}.Register(new global::{fullName}());\n";

    /// <summary>A registration of <paramref name="fullName"/> inside an <c>if</c> on one <c>KernelFeatures</c> property.</summary>
    /// <param name="feature">The <c>KernelFeatures</c> member.</param>
    /// <param name="fullName">The driver's full type name without <c>global::</c>.</param>
    public static string GuardedRegistration(string feature, string fullName) =>
        $"        if ({Features}.{feature})\n        {{\n"
        + $"            {Registry}.Register(new global::{fullName}());\n"
        + "        }\n";
}
