// This code is licensed under the BSD 3-Clause license (see LICENSE for details)

using Cosmos.Kernel.SourceGenerators;

namespace Cosmos.Tests.SourceGenerators;

/// <summary>
/// The exact text the generators are expected to emit, assembled the same way
/// a reader would write it by hand, so a test states the manifest it wants
/// as a list of registrations.
/// </summary>
internal static class GeneratedText
{
    private const string Registry = "global::Cosmos.Kernel.HAL.DriverKit.DriverRegistry";
    private const string Features = "global::Cosmos.Kernel.System.KernelFeatures";
    private const string VisualBasicRegistry = "Global.Cosmos.Kernel.HAL.DriverKit.DriverRegistry";
    private const string VisualBasicFeatures = "Global.Cosmos.Kernel.System.KernelFeatures";

    /// <summary>The whole of <c>CosmosEntryPoint.g.cs</c> for <paramref name="kernelClass"/>.</summary>
    /// <param name="kernelClass">The kernel type the entry point constructs.</param>
    public static string EntryPoint(string kernelClass)
    {
        return "// <auto-generated/>\n"
            + "namespace Cosmos.Kernel.System.Internal;\n\n"
            + "/// <summary>The kernel's entry point: registers the drivers in the manifest, then the kernel, and starts it.</summary>\n"
            + GeneratedCodeAttribute(typeof(CosmosEntryPointGenerator)) + "\n"
            + "public static class CosmosEntryPoint\n{\n"
            + "    /// <summary>Called by the runtime startup code once the managed world is up.</summary>\n"
            + "    public static void Main()\n    {\n"
            + "        global::Cosmos.Kernel.System.Internal.DriverManifest.Register();\n"
            + $"        global::Cosmos.Kernel.System.Internal.KernelEntry.Start(new global::{kernelClass}());\n"
            + "    }\n}\n";
    }

    /// <summary>The whole of <c>DriverManifest.g.cs</c> whose <c>Register</c> body is <paramref name="statements"/>, in order.</summary>
    /// <param name="statements">Statements from <see cref="Registration"/> and <see cref="GuardedRegistration"/>; none for an empty manifest.</param>
    public static string Manifest(params string[] statements)
    {
        return "// <auto-generated/>\n"
            + "// The driver registry is on the experimental driver kit seam (COSMOS0003).\n"
            + "// This file is generated, so it acknowledges the seam for itself alone;\n"
            + "// a driver this kernel declares still meets the diagnostic in its own code.\n"
            + "#pragma warning disable COSMOS0003\n"
            + "namespace Cosmos.Kernel.System.Internal;\n\n"
            + "/// <summary>The drivers this kernel carries, registered in manifest order before the kernel starts.</summary>\n"
            + GeneratedCodeAttribute(typeof(DriverManifestGenerator)) + "\n"
            + "internal static class DriverManifest\n{\n"
            + "    /// <summary>Registers every driver the manifest lists with the driver registry.</summary>\n"
            + "    public static void Register()\n    {\n"
            + string.Concat(statements)
            + "    }\n}\n";
    }

    /// <summary>An unguarded registration of <paramref name="fullName"/>.</summary>
    /// <param name="fullName">The driver's full type name without <c>global::</c>.</param>
    public static string Registration(string fullName) =>
        $"        {Registry}.Register(new global::{fullName}());\n";

    /// <summary>A registration of <paramref name="fullName"/> inside an <c>if</c> on one <c>KernelFeatures</c> property.</summary>
    /// <param name="feature">The <c>KernelFeatures</c> member.</param>
    /// <param name="fullName">The driver's full type name without <c>global::</c>.</param>
    public static string GuardedRegistration(string feature, string fullName) =>
        $"        if ({Features}.{feature})\n        {{\n"
        + $"            {Registry}.Register(new global::{fullName}());\n"
        + "        }\n";

    /// <summary>The whole of <c>CosmosEntryPoint.g.vb</c> for <paramref name="kernelClass"/>.</summary>
    /// <param name="kernelClass">The kernel type the entry point constructs.</param>
    public static string VisualBasicEntryPoint(string kernelClass)
    {
        return "' <auto-generated/>\n"
            + "Namespace Global.Cosmos.Kernel.System.Internal\n\n"
            + "    ''' <summary>The kernel's entry point: registers the drivers in the manifest, then the kernel, and starts it.</summary>\n"
            + $"    {VisualBasicGeneratedCodeAttribute(typeof(CosmosEntryPointGenerator))}\n"
            + "    Public Module CosmosEntryPoint\n"
            + "        ''' <summary>Called by the runtime startup code once the managed world is up.</summary>\n"
            + "        Public Sub Main()\n"
            + "            Global.Cosmos.Kernel.System.Internal.DriverManifest.Register()\n"
            + $"            Global.Cosmos.Kernel.System.Internal.KernelEntry.Start(New Global.{kernelClass}())\n"
            + "        End Sub\n"
            + "    End Module\n"
            + "End Namespace\n";
    }

    /// <summary>The whole of <c>DriverManifest.g.vb</c> whose <c>Register</c> body is <paramref name="statements"/>, in order.</summary>
    /// <param name="statements">Statements from <see cref="VisualBasicRegistration"/> and <see cref="VisualBasicGuardedRegistration"/>; none for an empty manifest.</param>
    public static string VisualBasicManifest(params string[] statements)
    {
        return "' <auto-generated/>\n"
            + "' The driver registry is on the experimental driver kit seam (COSMOS0003).\n"
            + "' This file is generated, so it acknowledges the seam for itself alone;\n"
            + "' a driver this kernel declares still meets the diagnostic in its own code.\n"
            + "#Disable Warning COSMOS0003\n"
            + "Namespace Global.Cosmos.Kernel.System.Internal\n\n"
            + "    ''' <summary>The drivers this kernel carries, registered in manifest order before the kernel starts.</summary>\n"
            + $"    {VisualBasicGeneratedCodeAttribute(typeof(DriverManifestGenerator))}\n"
            + "    Friend Module DriverManifest\n"
            + "        ''' <summary>Registers every driver the manifest lists with the driver registry.</summary>\n"
            + "        Public Sub Register()\n"
            + string.Concat(statements)
            + "        End Sub\n"
            + "    End Module\n"
            + "End Namespace\n";
    }

    /// <summary>An unguarded registration of <paramref name="fullName"/> in a Visual Basic manifest.</summary>
    /// <param name="fullName">The driver's full type name without <c>Global</c>.</param>
    public static string VisualBasicRegistration(string fullName)
    {
        return $"            {VisualBasicRegistry}.Register(New Global.{fullName}())\n";
    }

    /// <summary>A registration of <paramref name="fullName"/> inside an <c>If</c> on one <c>KernelFeatures</c> property, in a Visual Basic manifest.</summary>
    /// <param name="feature">The <c>KernelFeatures</c> member.</param>
    /// <param name="fullName">The driver's full type name without <c>Global</c>.</param>
    public static string VisualBasicGuardedRegistration(string feature, string fullName)
    {
        return $"            If {VisualBasicFeatures}.{feature} Then\n"
            + $"                {VisualBasicRegistry}.Register(New Global.{fullName}())\n"
            + "            End If\n";
    }

    /// <summary>The <c>[GeneratedCode]</c> line, stamped with the name and assembly version of the generator that emits the file.</summary>
    /// <param name="generator">The generator that emits the file.</param>
    private static string GeneratedCodeAttribute(Type generator)
    {
        return $"[global::System.CodeDom.Compiler.GeneratedCode(\"{generator.FullName}\", \"{generator.Assembly.GetName().Version}\")]";
    }

    /// <summary>The <c>&lt;GeneratedCode&gt;</c> line of a Visual Basic file, stamped the way <see cref="GeneratedCodeAttribute"/> stamps a C# one.</summary>
    /// <param name="generator">The generator that emits the file.</param>
    private static string VisualBasicGeneratedCodeAttribute(Type generator)
    {
        return $"<Global.System.CodeDom.Compiler.GeneratedCode(\"{generator.FullName}\", \"{generator.Assembly.GetName().Version}\")>";
    }
}
