use32
org 0x200000
			mov dword EAX, EAX
			mov dword EAX, EBX
			mov dword EAX, ECX
			mov dword EAX, EDX
			mov dword EAX, EDI
			mov dword EAX, ESI
			mov dword EAX, EBP
			mov dword EAX, ESP
			mov dword EBX, EAX
			mov dword EBX, EBX
			mov dword EBX, ECX
			mov dword EBX, EDX
			mov dword EBX, EDI
			mov dword EBX, ESI
			mov dword EBX, EBP
			mov dword EBX, ESP
			mov dword ECX, EAX
			mov dword ECX, EBX
			mov dword ECX, ECX
			mov dword ECX, EDX
			mov dword ECX, EDI
			mov dword ECX, ESI
			mov dword ECX, EBP
			mov dword ECX, ESP
			mov dword EDX, EAX
			mov dword EDX, EBX
			mov dword EDX, ECX
			mov dword EDX, EDX
			mov dword EDX, EDI
			mov dword EDX, ESI
			mov dword EDX, EBP
			mov dword EDX, ESP
			mov dword EDI, EAX
			mov dword EDI, EBX
			mov dword EDI, ECX
			mov dword EDI, EDX
			mov dword EDI, EDI
			mov dword EDI, ESI
			mov dword EDI, EBP
			mov dword EDI, ESP
			mov dword ESI, EAX
			mov dword ESI, EBX
			mov dword ESI, ECX
			mov dword ESI, EDX
			mov dword ESI, EDI
			mov dword ESI, ESI
			mov dword ESI, EBP
			mov dword ESI, ESP
			mov dword EBP, EAX
			mov dword EBP, EBX
			mov dword EBP, ECX
			mov dword EBP, EDX
			mov dword EBP, EDI
			mov dword EBP, ESI
			mov dword EBP, EBP
			mov dword EBP, ESP
			mov dword ESP, EAX
			mov dword ESP, EBX
			mov dword ESP, ECX
			mov dword ESP, EDX
			mov dword ESP, EDI
			mov dword ESP, ESI
			mov dword ESP, EBP
			mov dword ESP, ESP
