#!/usr/bin/env bash
# Rebuilds the two wasm modules the suite runs and regenerates WasmModules.cs,
# which carries their bytes into the kernel. Needs clang and wasm-ld with the
# wasm32 target (LLVM 18 was used).
set -euo pipefail

cd "$(dirname "$0")"

FLAGS=(--target=wasm32 -O2 -nostdlib -fno-builtin -ffp-contract=off -Wl,--no-entry -Wl,--strip-all)
OUT=$(mktemp -d)
trap 'rm -rf "$OUT"' EXIT

clang "${FLAGS[@]}" -o "$OUT/bench.wasm" bench.c
clang "${FLAGS[@]}" -Wl,--allow-undefined -o "$OUT/host.wasm" host.c

emit() {
    od -An -v -tx1 "$1" | tr -s ' \n' ' ' | sed 's/^ //; s/ $//' | tr ' ' '\n' \
        | awk '{ printf "%s0x%s,", (NR % 16 == 1 ? "\n        " : " "), $1 }' | sed '$ s/,$//'
}

cat > WasmModules.cs <<EOF
// This code is licensed under the BSD 3-Clause license (see LICENSE for details)

namespace Cosmos.Kernel.Tests.Wasm.Modules;

/// <summary>
/// The modules every VM runs, generated by build.sh from bench.c and host.c.
/// </summary>
internal static class WasmModules
{
    /// <summary>The compute workloads; imports nothing.</summary>
    public static ReadOnlySpan<byte> Bench =>
    [$(emit "$OUT/bench.wasm")
    ];

    /// <summary>The host-call loop; imports <c>env.host_add</c>.</summary>
    public static ReadOnlySpan<byte> Host =>
    [$(emit "$OUT/host.wasm")
    ];
}
EOF
