
; COMDLG32 API calls

import comdlg32,\
       ChooseColorA,'ChooseColorA',\
       ChooseColorW,'ChooseColorW',\
       ChooseFontA,'ChooseFontA',\
       ChooseFontW,'ChooseFontW',\
       CommDlgExtendedError,'CommDlgExtendedError',\
       FindTextA,'FindTextA',\
       FindTextW,'FindTextW',\
       FormatCharDlgProc,'FormatCharDlgProc',\
       GetFileTitleA,'GetFileTitleA',\
       GetFileTitleW,'GetFileTitleW',\
       GetOpenFileNameA,'GetOpenFileNameA',\
       GetOpenFileNameW,'GetOpenFileNameW',\
       GetSaveFileNameA,'GetSaveFileNameA',\
       GetSaveFileNameW,'GetSaveFileNameW',\
       LoadAlterBitmap,'LoadAlterBitmap',\
       PageSetupDlgA,'PageSetupDlgA',\
       PageSetupDlgW,'PageSetupDlgW',\
       PrintDlgA,'PrintDlgA',\
       PrintDlgW,'PrintDlgW',\
       ReplaceTextA,'ReplaceTextA',\
       ReplaceTextW,'ReplaceTextW',\
       WantArrows,'WantArrows',\
       dwLBSubclass,'dwLBSubclass',\
       dwOKSubclass,'dwOKSubclass'

api ChooseColor,\
    ChooseFont,\
    FindText,\
    GetFileTitle,\
    GetOpenFileName,\
    GetSaveFileName,\
    PageSetupDlg,\
    PrintDlg,\
    ReplaceText
