use32
org 0x200000
			sub dword EAX, EAX
			sub dword EAX, EBX
			sub dword EAX, ECX
			sub dword EAX, EDX
			sub dword EAX, EDI
			sub dword EAX, ESI
			sub dword EAX, EBP
			sub dword EAX, ESP
			sub dword EBX, EAX
			sub dword EBX, EBX
			sub dword EBX, ECX
			sub dword EBX, EDX
			sub dword EBX, EDI
			sub dword EBX, ESI
			sub dword EBX, EBP
			sub dword EBX, ESP
			sub dword ECX, EAX
			sub dword ECX, EBX
			sub dword ECX, ECX
			sub dword ECX, EDX
			sub dword ECX, EDI
			sub dword ECX, ESI
			sub dword ECX, EBP
			sub dword ECX, ESP
			sub dword EDX, EAX
			sub dword EDX, EBX
			sub dword EDX, ECX
			sub dword EDX, EDX
			sub dword EDX, EDI
			sub dword EDX, ESI
			sub dword EDX, EBP
			sub dword EDX, ESP
			sub dword EDI, EAX
			sub dword EDI, EBX
			sub dword EDI, ECX
			sub dword EDI, EDX
			sub dword EDI, EDI
			sub dword EDI, ESI
			sub dword EDI, EBP
			sub dword EDI, ESP
			sub dword ESI, EAX
			sub dword ESI, EBX
			sub dword ESI, ECX
			sub dword ESI, EDX
			sub dword ESI, EDI
			sub dword ESI, ESI
			sub dword ESI, EBP
			sub dword ESI, ESP
			sub dword EBP, EAX
			sub dword EBP, EBX
			sub dword EBP, ECX
			sub dword EBP, EDX
			sub dword EBP, EDI
			sub dword EBP, ESI
			sub dword EBP, EBP
			sub dword EBP, ESP
			sub dword ESP, EAX
			sub dword ESP, EBX
			sub dword ESP, ECX
			sub dword ESP, EDX
			sub dword ESP, EDI
			sub dword ESP, ESI
			sub dword ESP, EBP
			sub dword ESP, ESP
