use32
org 0x200000
			sub word AX, AX
			sub word AX, BX
			sub word AX, CX
			sub word AX, DX
			sub word AX, DI
			sub word AX, SI
			sub word AX, BP
			sub word AX, SP
			sub word BX, AX
			sub word BX, BX
			sub word BX, CX
			sub word BX, DX
			sub word BX, DI
			sub word BX, SI
			sub word BX, BP
			sub word BX, SP
			sub word CX, AX
			sub word CX, BX
			sub word CX, CX
			sub word CX, DX
			sub word CX, DI
			sub word CX, SI
			sub word CX, BP
			sub word CX, SP
			sub word DX, AX
			sub word DX, BX
			sub word DX, CX
			sub word DX, DX
			sub word DX, DI
			sub word DX, SI
			sub word DX, BP
			sub word DX, SP
			sub word DI, AX
			sub word DI, BX
			sub word DI, CX
			sub word DI, DX
			sub word DI, DI
			sub word DI, SI
			sub word DI, BP
			sub word DI, SP
			sub word SI, AX
			sub word SI, BX
			sub word SI, CX
			sub word SI, DX
			sub word SI, DI
			sub word SI, SI
			sub word SI, BP
			sub word SI, SP
			sub word BP, AX
			sub word BP, BX
			sub word BP, CX
			sub word BP, DX
			sub word BP, DI
			sub word BP, SI
			sub word BP, BP
			sub word BP, SP
			sub word SP, AX
			sub word SP, BX
			sub word SP, CX
			sub word SP, DX
			sub word SP, DI
			sub word SP, SI
			sub word SP, BP
			sub word SP, SP
