<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <IncludeBuildOutput>true</IncludeBuildOutput>
    <SuppressDependenciesWhenPacking>false</SuppressDependenciesWhenPacking>
  </PropertyGroup>
  <PropertyGroup>
    <PackageId>Cosmos.Build.Analyzer.Patcher</PackageId>
    <PackageLicenseExpression>BSD-3-Clause</PackageLicenseExpression>
    <!-- <PackageIconUrl>http://ICON_URL_HERE_OR_DELETE_THIS_LINE</PackageIconUrl> -->
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <Description>Cosmos.Patcher.Analyzer</Description>
    <PackageReleaseNotes>Release</PackageReleaseNotes>
    <Copyright>Copyright</Copyright>
    <PackageTags>Cosmos.Patcher.Analyzer, analyzers</PackageTags>
    <DevelopmentDependency>true</DevelopmentDependency>
    <NoPackageAnalysis>true</NoPackageAnalysis>
    <TargetsForTfmSpecificContentInPackage>$(TargetsForTfmSpecificContentInPackage);_AddAnalyzersToOutput</TargetsForTfmSpecificContentInPackage>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Cosmos.Build.Analyzer.Patcher.CodeFixes\Cosmos.Build.Analyzer.Patcher.CodeFixes.csproj" />
    <ProjectReference Include="..\Cosmos.Build.Analyzer.Patcher\Cosmos.Build.Analyzer.Patcher.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="tools\*.ps1" CopyToOutputDirectory="PreserveNewest" Pack="true" PackagePath=""/>
  </ItemGroup>
  <Target Name="_AddAnalyzersToOutput">
    <ItemGroup>
      <TfmSpecificPackageFile Include="$(OutputPath)/*.dll" PackagePath="analyzers/dotnet/cs" />

    </ItemGroup>
  </Target>
</Project>