using System;

namespace Cosmos.Kernel.HAL.Devices.Graphic.SVGAII;

internal enum SVGA3dDeclMethod
{
    SVGA3D_DECLMETHOD_DEFAULT = 0,
    SVGA3D_DECLMETHOD_PARTIALU,
    SVGA3D_DECLMETHOD_PARTIALV,
    SVGA3D_DECLMETHOD_CROSSUV,
    SVGA3D_DECLMETHOD_UV,
    SVGA3D_DECLMETHOD_LOOKUP,
    SVGA3D_DECLMETHOD_LOOKUPPRESAMPLED,
}
