// This code is licensed under the BSD 3-Clause license (see LICENSE for details)

using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Cosmos.Kernel.SourceGenerators;

/// <summary>
/// Generates <c>CosmosEntryPoint.g.cs</c>, the kernel's <c>Main</c>: it
/// registers the drivers <see cref="DriverManifestGenerator"/> lists, then
/// constructs the kernel the <c>CosmosKernelClass</c> build property names
/// and starts it. Nothing is generated when the property is empty. The
/// pipeline reads that property alone, so an edit to the kernel's sources
/// or to its driver policy leaves the generated file cached.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class CosmosEntryPointGenerator : IIncrementalGenerator
{
    private const string HintName = "CosmosEntryPoint.g.cs";

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValueProvider<string?> kernelClass = context.AnalyzerConfigOptionsProvider
            .Select(static (provider, _) => GeneratorOptions.From(provider.GlobalOptions).KernelClass);

        context.RegisterSourceOutput(kernelClass, static (productionContext, value) =>
        {
            if (value is not null)
            {
                productionContext.AddSource(HintName, SourceText.From(Source(value), Encoding.UTF8));
            }
        });
    }

    private static string Source(string kernelClass)
    {
        StringBuilder builder = new();
        builder.Append("// <auto-generated/>\n");
        builder.Append("namespace Cosmos.Kernel.System.Internal;\n\n");
        builder.Append("/// <summary>The kernel's entry point: registers the drivers in the manifest, then the kernel, and starts it.</summary>\n");
        builder.Append(GeneratedCode.Attribute(typeof(CosmosEntryPointGenerator))).Append('\n');
        builder.Append("public static class CosmosEntryPoint\n{\n");
        builder.Append("    /// <summary>Called by the runtime startup code once the managed world is up.</summary>\n");
        builder.Append("    public static void Main()\n    {\n");
        builder.Append("        global::Cosmos.Kernel.System.Internal.DriverManifest.Register();\n");
        builder.Append("        global::Cosmos.Kernel.System.Internal.KernelEntry.Start(new global::").Append(kernelClass).Append("());\n");
        builder.Append("    }\n}\n");
        return builder.ToString();
    }
}
