// This code is licensed under the BSD 3-Clause license (see LICENSE for details)

using System.Text;

namespace Cosmos.Kernel.SourceGenerators;

/// <summary>
/// Writes the generated files of a C# kernel: a file-scoped namespace, static
/// classes, and every type name rooted at <c>global::</c>.
/// </summary>
internal sealed class CSharpSourceWriter : SourceWriter
{
    /// <inheritdoc/>
    public override string FileExtension => ".g.cs";

    /// <summary>The one instance; the writer holds no state.</summary>
    public static CSharpSourceWriter Instance { get; } = new();

    private CSharpSourceWriter()
    {
    }

    /// <inheritdoc/>
    public override string EntryPoint(string kernelClass)
    {
        StringBuilder builder = new();
        builder.Append("// <auto-generated/>\n");
        builder.Append("namespace ").Append(InternalNamespace).Append(";\n\n");
        builder.Append("/// <summary>").Append(EntryPointSummary).Append("</summary>\n");
        builder.Append(GeneratedCodeAttribute(typeof(CosmosEntryPointGenerator))).Append('\n');
        builder.Append("public static class CosmosEntryPoint\n{\n");
        builder.Append("    /// <summary>").Append(MainSummary).Append("</summary>\n");
        builder.Append("    public static void Main()\n    {\n");
        builder.Append("        global::").Append(InternalNamespace).Append(".DriverManifest.Register();\n");
        builder.Append("        global::").Append(KernelEntryType).Append(".Start(new global::").Append(kernelClass).Append("());\n");
        builder.Append("    }\n}\n");
        return builder.ToString();
    }

    /// <inheritdoc/>
    public override string Manifest(IReadOnlyList<DriverCandidate> registered)
    {
        StringBuilder builder = new();
        builder.Append("// <auto-generated/>\n");
        foreach (string line in s_seamAcknowledgement)
        {
            builder.Append("// ").Append(line).Append('\n');
        }

        builder.Append("#pragma warning disable ").Append(SeamDiagnosticId).Append('\n');
        builder.Append("namespace ").Append(InternalNamespace).Append(";\n\n");
        builder.Append("/// <summary>").Append(ManifestSummary).Append("</summary>\n");
        builder.Append(GeneratedCodeAttribute(typeof(DriverManifestGenerator))).Append('\n');
        builder.Append("internal static class DriverManifest\n{\n");
        builder.Append("    /// <summary>").Append(RegisterSummary).Append("</summary>\n");
        builder.Append("    public static void Register()\n    {\n");
        foreach (DriverCandidate candidate in registered)
        {
            if (candidate.FeatureGuard is null)
            {
                builder.Append("        global::").Append(RegistryType).Append(".Register(new global::").Append(candidate.FullName).Append("());\n");
                continue;
            }

            builder.Append("        if (global::").Append(FeaturesType).Append('.').Append(candidate.FeatureGuard).Append(")\n        {\n");
            builder.Append("            global::").Append(RegistryType).Append(".Register(new global::").Append(candidate.FullName).Append("());\n");
            builder.Append("        }\n");
        }

        builder.Append("    }\n}\n");
        return builder.ToString();
    }

    private static string GeneratedCodeAttribute(Type generator)
    {
        return $"[global::System.CodeDom.Compiler.GeneratedCode({GeneratedCode.Arguments(generator)})]";
    }
}
