// This code is licensed under the BSD 3-Clause license (see LICENSE for details)

using System.Text;

namespace Cosmos.Kernel.SourceGenerators;

/// <summary>
/// Writes the generated files of a Visual Basic kernel. A Visual Basic
/// project puts every namespace it declares under its root namespace, so the
/// files declare theirs from <c>Global</c> to land in
/// <c>Cosmos.Kernel.System.Internal</c> itself, where the SDK's startup
/// object names the entry point. The types are modules, the language's
/// static classes.
/// </summary>
internal sealed class VisualBasicSourceWriter : SourceWriter
{
    /// <inheritdoc/>
    public override string FileExtension => ".g.vb";

    /// <summary>The one instance; the writer holds no state.</summary>
    public static VisualBasicSourceWriter Instance { get; } = new();

    private VisualBasicSourceWriter()
    {
    }

    /// <inheritdoc/>
    public override string EntryPoint(string kernelClass)
    {
        StringBuilder builder = new();
        builder.Append("' <auto-generated/>\n");
        builder.Append("Namespace Global.").Append(InternalNamespace).Append("\n\n");
        builder.Append("    ''' <summary>").Append(EntryPointSummary).Append("</summary>\n");
        builder.Append("    ").Append(GeneratedCodeAttribute(typeof(CosmosEntryPointGenerator))).Append('\n');
        builder.Append("    Public Module CosmosEntryPoint\n");
        builder.Append("        ''' <summary>").Append(MainSummary).Append("</summary>\n");
        builder.Append("        Public Sub Main()\n");
        builder.Append("            Global.").Append(InternalNamespace).Append(".DriverManifest.Register()\n");
        builder.Append("            Global.").Append(KernelEntryType).Append(".Start(New Global.").Append(kernelClass).Append("())\n");
        builder.Append("        End Sub\n");
        builder.Append("    End Module\n");
        builder.Append("End Namespace\n");
        return builder.ToString();
    }

    /// <inheritdoc/>
    public override string Manifest(IReadOnlyList<DriverCandidate> registered)
    {
        StringBuilder builder = new();
        builder.Append("' <auto-generated/>\n");
        foreach (string line in s_seamAcknowledgement)
        {
            builder.Append("' ").Append(line).Append('\n');
        }

        builder.Append("#Disable Warning ").Append(SeamDiagnosticId).Append('\n');
        builder.Append("Namespace Global.").Append(InternalNamespace).Append("\n\n");
        builder.Append("    ''' <summary>").Append(ManifestSummary).Append("</summary>\n");
        builder.Append("    ").Append(GeneratedCodeAttribute(typeof(DriverManifestGenerator))).Append('\n');
        builder.Append("    Friend Module DriverManifest\n");
        builder.Append("        ''' <summary>").Append(RegisterSummary).Append("</summary>\n");
        builder.Append("        Public Sub Register()\n");
        foreach (DriverCandidate candidate in registered)
        {
            if (candidate.FeatureGuard is null)
            {
                builder.Append("            Global.").Append(RegistryType).Append(".Register(New Global.").Append(candidate.FullName).Append("())\n");
                continue;
            }

            builder.Append("            If Global.").Append(FeaturesType).Append('.').Append(candidate.FeatureGuard).Append(" Then\n");
            builder.Append("                Global.").Append(RegistryType).Append(".Register(New Global.").Append(candidate.FullName).Append("())\n");
            builder.Append("            End If\n");
        }

        builder.Append("        End Sub\n");
        builder.Append("    End Module\n");
        builder.Append("End Namespace\n");
        return builder.ToString();
    }

    private static string GeneratedCodeAttribute(Type generator)
    {
        return $"<Global.System.CodeDom.Compiler.GeneratedCode({GeneratedCode.Arguments(generator)})>";
    }
}
