use32
org 0x200000
			add dword EAX, EAX
			add dword EAX, EBX
			add dword EAX, ECX
			add dword EAX, EDX
			add dword EAX, EDI
			add dword EAX, ESI
			add dword EAX, EBP
			add dword EAX, ESP
			add dword EBX, EAX
			add dword EBX, EBX
			add dword EBX, ECX
			add dword EBX, EDX
			add dword EBX, EDI
			add dword EBX, ESI
			add dword EBX, EBP
			add dword EBX, ESP
			add dword ECX, EAX
			add dword ECX, EBX
			add dword ECX, ECX
			add dword ECX, EDX
			add dword ECX, EDI
			add dword ECX, ESI
			add dword ECX, EBP
			add dword ECX, ESP
			add dword EDX, EAX
			add dword EDX, EBX
			add dword EDX, ECX
			add dword EDX, EDX
			add dword EDX, EDI
			add dword EDX, ESI
			add dword EDX, EBP
			add dword EDX, ESP
			add dword EDI, EAX
			add dword EDI, EBX
			add dword EDI, ECX
			add dword EDI, EDX
			add dword EDI, EDI
			add dword EDI, ESI
			add dword EDI, EBP
			add dword EDI, ESP
			add dword ESI, EAX
			add dword ESI, EBX
			add dword ESI, ECX
			add dword ESI, EDX
			add dword ESI, EDI
			add dword ESI, ESI
			add dword ESI, EBP
			add dword ESI, ESP
			add dword EBP, EAX
			add dword EBP, EBX
			add dword EBP, ECX
			add dword EBP, EDX
			add dword EBP, EDI
			add dword EBP, ESI
			add dword EBP, EBP
			add dword EBP, ESP
			add dword ESP, EAX
			add dword ESP, EBX
			add dword ESP, ECX
			add dword ESP, EDX
			add dword ESP, EDI
			add dword ESP, ESI
			add dword ESP, EBP
			add dword ESP, ESP
