use32
org 0x200000
			add byte AL, AL
			add byte AL, AH
			add byte AL, BL
			add byte AL, BH
			add byte AL, CL
			add byte AL, CH
			add byte AL, DL
			add byte AL, DH
			add byte AH, AL
			add byte AH, AH
			add byte AH, BL
			add byte AH, BH
			add byte AH, CL
			add byte AH, CH
			add byte AH, DL
			add byte AH, DH
			add byte BL, AL
			add byte BL, AH
			add byte BL, BL
			add byte BL, BH
			add byte BL, CL
			add byte BL, CH
			add byte BL, DL
			add byte BL, DH
			add byte BH, AL
			add byte BH, AH
			add byte BH, BL
			add byte BH, BH
			add byte BH, CL
			add byte BH, CH
			add byte BH, DL
			add byte BH, DH
			add byte CL, AL
			add byte CL, AH
			add byte CL, BL
			add byte CL, BH
			add byte CL, CL
			add byte CL, CH
			add byte CL, DL
			add byte CL, DH
			add byte CH, AL
			add byte CH, AH
			add byte CH, BL
			add byte CH, BH
			add byte CH, CL
			add byte CH, CH
			add byte CH, DL
			add byte CH, DH
			add byte DL, AL
			add byte DL, AH
			add byte DL, BL
			add byte DL, BH
			add byte DL, CL
			add byte DL, CH
			add byte DL, DL
			add byte DL, DH
			add byte DH, AL
			add byte DH, AH
			add byte DH, BL
			add byte DH, BH
			add byte DH, CL
			add byte DH, CH
			add byte DH, DL
			add byte DH, DH
