; Generated at 6/26/2016 1:43:07 PM



			DebugStub_Const_Signature equ 427034631
			DebugStub_Const_Tracing_Off equ 0
			DebugStub_Const_Tracing_On equ 1
			DebugStub_Const_Status_Run equ 0
			DebugStub_Const_Status_Break equ 1
			DebugStub_Const_StepTrigger_None equ 0
			DebugStub_Const_StepTrigger_Into equ 1
			DebugStub_Const_StepTrigger_Over equ 2
			DebugStub_Const_StepTrigger_Out equ 3
			DebugStub_Const_Vs2Ds_Noop equ 0
			DebugStub_Const_Vs2Ds_TraceOff equ 1
			DebugStub_Const_Vs2Ds_TraceOn equ 2
			DebugStub_Const_Vs2Ds_Break equ 3
			DebugStub_Const_Vs2Ds_Continue equ 4
			DebugStub_Const_Vs2Ds_BreakOnAddress equ 6
			DebugStub_Const_Vs2Ds_BatchBegin equ 7
			DebugStub_Const_Vs2Ds_BatchEnd equ 8
			DebugStub_Const_Vs2Ds_StepInto equ 5
			DebugStub_Const_Vs2Ds_StepOver equ 11
			DebugStub_Const_Vs2Ds_StepOut equ 12
			DebugStub_Const_Vs2Ds_SendMethodContext equ 9
			DebugStub_Const_Vs2Ds_SendMemory equ 10
			DebugStub_Const_Vs2Ds_SendRegisters equ 13
			DebugStub_Const_Vs2Ds_SendFrame equ 14
			DebugStub_Const_Vs2Ds_SendStack equ 15
			DebugStub_Const_Vs2Ds_SetAsmBreak equ 16
			DebugStub_Const_Vs2Ds_Ping equ 17
			DebugStub_Const_Vs2Ds_AsmStepInto equ 18
			DebugStub_Const_Vs2Ds_SetINT3 equ 19
			DebugStub_Const_Vs2Ds_ClearINT3 equ 20
			DebugStub_Const_Vs2Ds_Max equ 21
			DebugStub_Const_Ds2Vs_Noop equ 0
			DebugStub_Const_Ds2Vs_TracePoint equ 1
			DebugStub_Const_Ds2Vs_Message equ 192
			DebugStub_Const_Ds2Vs_BreakPoint equ 3
			DebugStub_Const_Ds2Vs_Error equ 4
			DebugStub_Const_Ds2Vs_Pointer equ 5
			DebugStub_Const_Ds2Vs_Started equ 6
			DebugStub_Const_Ds2Vs_MethodContext equ 7
			DebugStub_Const_Ds2Vs_MemoryData equ 8
			DebugStub_Const_Ds2Vs_CmdCompleted equ 9
			DebugStub_Const_Ds2Vs_Registers equ 10
			DebugStub_Const_Ds2Vs_Frame equ 11
			DebugStub_Const_Ds2Vs_Stack equ 12
			DebugStub_Const_Ds2Vs_Pong equ 13
			DebugStub_Const_Ds2Vs_BreakPointAsm equ 14
			DebugStub_Const_Ds2Vs_StackCorruptionOccurred equ 15
			DebugStub_Const_Ds2Vs_MessageBox equ 16
			DebugStub_Const_Ds2Vs_NullReferenceOccurred equ 17
			DebugStub_Const_Ds2Vs_SimpleNumber equ 18
			DebugStub_Const_Ds2Vs_SimpleLongNumber equ 19
			DebugStub_Const_Ds2Vs_ComplexNumber equ 20
			DebugStub_Const_Ds2Vs_ComplexLongNumber equ 21
			DebugStub_Const_Ds2Vs_StackOverflowOccurred equ 22
			DebugStub_Const_Ds2Vs_InterruptOccurred equ 23
			DebugStub_Const_Ds2Vs_CoreDump equ 24
			DebugStub_Const_Ds2Vs_KernelPanic equ 25

