use32
org 0x200000
			add word AX, AX
			add word AX, BX
			add word AX, CX
			add word AX, DX
			add word AX, DI
			add word AX, SI
			add word AX, BP
			add word AX, SP
			add word BX, AX
			add word BX, BX
			add word BX, CX
			add word BX, DX
			add word BX, DI
			add word BX, SI
			add word BX, BP
			add word BX, SP
			add word CX, AX
			add word CX, BX
			add word CX, CX
			add word CX, DX
			add word CX, DI
			add word CX, SI
			add word CX, BP
			add word CX, SP
			add word DX, AX
			add word DX, BX
			add word DX, CX
			add word DX, DX
			add word DX, DI
			add word DX, SI
			add word DX, BP
			add word DX, SP
			add word DI, AX
			add word DI, BX
			add word DI, CX
			add word DI, DX
			add word DI, DI
			add word DI, SI
			add word DI, BP
			add word DI, SP
			add word SI, AX
			add word SI, BX
			add word SI, CX
			add word SI, DX
			add word SI, DI
			add word SI, SI
			add word SI, BP
			add word SI, SP
			add word BP, AX
			add word BP, BX
			add word BP, CX
			add word BP, DX
			add word BP, DI
			add word BP, SI
			add word BP, BP
			add word BP, SP
			add word SP, AX
			add word SP, BX
			add word SP, CX
			add word SP, DX
			add word SP, DI
			add word SP, SI
			add word SP, BP
			add word SP, SP
