namespace Cosmos.Kernel.HAL.Pci.Enums;

internal enum Config : byte
{
    VendorId = 0,
    DeviceId = 2,
    Command = 4,
    Status = 6,
    RevisionId = 8,
    ProgIf = 9,
    SubClass = 10,
    Class = 11,
    CacheLineSize = 12,
    LatencyTimer = 13,
    HeaderType = 14,
    Bist = 15,
    Bar0 = 16,
    Bar1 = 20,
    PrimaryBusNo = 24,
    SecondaryBusNo = 25,
    SubBusNo = 26,
    SecondarLt = 27,
    IoBase = 28,
    IoLimit = 29,
    SecondaryStatus = 30,
    MemoryBase = 32,
    MemoryLimit = 34,
    PrefMemoryBase = 36,
    PrefMemoryLimit = 38,
    PrefBase32Upper = 40,
    PrefLimit32Upper = 44,
    PrefBase16Upper = 48,
    PrefLimit16Upper = 50,
    CapabilityPointer = 52,
    Reserved = 53,
    ExpRomBaseAddress = 56,
    InterruptLine = 60,
    InterruptPin = 61,
    BridgeControl = 62
};
