<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>Cosmos.Build.Analyzer.Patcher</RootNamespace>
    <OutputType>Library</OutputType>
    <!-- Avoid ID conflicts with the package project. -->
    <PackageId>_Cosmos.Build.Analyzer.Patcher</PackageId>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
<PackageReference Include="PolySharp">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <ProjectReference Include="../Cosmos.Build.API/Cosmos.Build.API.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <None Include="$(OutputPath)Cosmos.Build.API.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
  </ItemGroup>
  <ItemGroup>
          <TargetPathWithTargetPlatformMoniker Include="$(OutputPath)*.dll" IncludeRuntimeDependency="false" />
  </ItemGroup>
</Project>
