using System;


namespace Cosmos.IL2CPU.X86.IL
{
    [Cosmos.IL2CPU.OpCode( ILOpCode.Code.Calli )]
    public class Calli : ILOp
    {
        public Calli( Cosmos.Assembler.Assembler aAsmblr )
            : base( aAsmblr )
        {
        }

        public override void Execute(_MethodInfo aMethod, ILOpCode aOpCode )
        {
            throw new NotImplementedException("Cosmos.IL2CPU.x86->IL->Calli.cs->Error: The Calli op-code has not been implemented yet!");
        }


        // using System;
        // using System.IO;
        // 
        // 
        // using CPU = Cosmos.Assembler.x86;
        // 
        // namespace Cosmos.IL2CPU.IL.X86 {
        // 	[Cosmos.Assembler.OpCode(OpCodeEnum.Calli)]
        // 	public class Calli: Op {
        // 		public Calli(ILReader aReader, MethodInformation aMethodInfo)
        // 			: base(aReader, aMethodInfo) {
        // 		}
        // 		public override void DoAssemble() {
        // 			throw new NotImplementedException("This file has been autogenerated and not been changed afterwards!");
        // 		}
        // 	}
        // }

    }
}
