use32
org 0x200000
			mov word AX, AX
			mov word AX, BX
			mov word AX, CX
			mov word AX, DX
			mov word AX, DI
			mov word AX, SI
			mov word AX, BP
			mov word AX, SP
			mov word BX, AX
			mov word BX, BX
			mov word BX, CX
			mov word BX, DX
			mov word BX, DI
			mov word BX, SI
			mov word BX, BP
			mov word BX, SP
			mov word CX, AX
			mov word CX, BX
			mov word CX, CX
			mov word CX, DX
			mov word CX, DI
			mov word CX, SI
			mov word CX, BP
			mov word CX, SP
			mov word DX, AX
			mov word DX, BX
			mov word DX, CX
			mov word DX, DX
			mov word DX, DI
			mov word DX, SI
			mov word DX, BP
			mov word DX, SP
			mov word DI, AX
			mov word DI, BX
			mov word DI, CX
			mov word DI, DX
			mov word DI, DI
			mov word DI, SI
			mov word DI, BP
			mov word DI, SP
			mov word SI, AX
			mov word SI, BX
			mov word SI, CX
			mov word SI, DX
			mov word SI, DI
			mov word SI, SI
			mov word SI, BP
			mov word SI, SP
			mov word BP, AX
			mov word BP, BX
			mov word BP, CX
			mov word BP, DX
			mov word BP, DI
			mov word BP, SI
			mov word BP, BP
			mov word BP, SP
			mov word SP, AX
			mov word SP, BX
			mov word SP, CX
			mov word SP, DX
			mov word SP, DI
			mov word SP, SI
			mov word SP, BP
			mov word SP, SP
