use32
org 0x200000
			mov byte AL, AL
			mov byte AL, AH
			mov byte AL, BL
			mov byte AL, BH
			mov byte AL, CL
			mov byte AL, CH
			mov byte AL, DL
			mov byte AL, DH
			mov byte AH, AL
			mov byte AH, AH
			mov byte AH, BL
			mov byte AH, BH
			mov byte AH, CL
			mov byte AH, CH
			mov byte AH, DL
			mov byte AH, DH
			mov byte BL, AL
			mov byte BL, AH
			mov byte BL, BL
			mov byte BL, BH
			mov byte BL, CL
			mov byte BL, CH
			mov byte BL, DL
			mov byte BL, DH
			mov byte BH, AL
			mov byte BH, AH
			mov byte BH, BL
			mov byte BH, BH
			mov byte BH, CL
			mov byte BH, CH
			mov byte BH, DL
			mov byte BH, DH
			mov byte CL, AL
			mov byte CL, AH
			mov byte CL, BL
			mov byte CL, BH
			mov byte CL, CL
			mov byte CL, CH
			mov byte CL, DL
			mov byte CL, DH
			mov byte CH, AL
			mov byte CH, AH
			mov byte CH, BL
			mov byte CH, BH
			mov byte CH, CL
			mov byte CH, CH
			mov byte CH, DL
			mov byte CH, DH
			mov byte DL, AL
			mov byte DL, AH
			mov byte DL, BL
			mov byte DL, BH
			mov byte DL, CL
			mov byte DL, CH
			mov byte DL, DL
			mov byte DL, DH
			mov byte DH, AL
			mov byte DH, AH
			mov byte DH, BL
			mov byte DH, BH
			mov byte DH, CL
			mov byte DH, CH
			mov byte DH, DL
			mov byte DH, DH
