name: Build Docs

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    # - name: Setup dotnet
    #   uses: actions/setup-dotnet@v1
    #   with:
    #     dotnet-version: 3.1.101
    # - name: Build docs
    #   run: dotnet build ./Docs/Cosmos.Docs.csproj
    - name: Build docs
      uses: nikeee/docfx-action@v1.0.0
      with:
        args: ./Docs/docfx.json
    - name: Publish to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GH_PAGES }}
        external_repository: CosmosOS/cosmosos.github.io
        publish_branch: master
        publish_dir: ./Docs/_site
